#!/usr/bin/env python

import socket, time, interface

i = interface.AsynchronousInterface('ecdsa.org', 50001)
i.start()
i.send([('numblocks.subscribe',[])])

while True:
    r = i.responses.get(True, 100000000000)
    print r.get('result')
