#!/bin/bash
RED='\033[0;31m'
BLUE='\033[0,34m'
NC='\033[0m' # No Color
function info {
    printf "\rð ${BLUE}INFO:${NC} ${1}\n"
}
function fail {
    printf "\rð ${RED}ERROR:${NC} ${1}\n"
    exit 1
}

build_dir=$(dirname "$0")
test -n "$build_dir" -a -d "$build_dir" || exit
cd $build_dir/../..

export PYTHONHASHSEED=22
VERSION=`git describe --tags`
PYTHON_VERSION=3.6.4


info "Installing Python $PYTHON_VERSION"
export PATH="~/.pyenv/bin:~/.pyenv/shims:$PATH:~/Library/Python/3.6/bin"
if [ -d "~/.pyenv" ]; then
  pyenv update
else
  curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash > /dev/null 2>&1
fi
PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install -s $PYTHON_VERSION && \
pyenv global $PYTHON_VERSION || \
fail "Unable to use Python $PYTHON_VERSION"


if ! which pyinstaller > /dev/null; then
  info "Installing pyinstaller"
  python3 -m pip install pyinstaller -I --user || fail "Could not install pyinstaller"
fi

info "Using these versions for building Electrum:"
sw_vers
python3 --version
echo -n "Pyinstaller "
pyinstaller --version

rm -rf ./dist

BUILDDIR=/tmp/electrum-build

rm  -rf /tmp/electrum-build > /dev/null 2>&1
mkdir /tmp/electrum-build

info "Downloading locale..."
git clone https://github.com/spesmilo/electrum-locale /tmp/electrum-build/electrum-locale
cp -R /tmp/electrum-build/electrum-locale/locale/ ./electrum/locale/

info "Downloading libusb..."
curl https://homebrew.bintray.com/bottles/libusb-1.0.22.el_capitan.bottle.tar.gz | \
tar xz --directory $BUILDDIR
cp $BUILDDIR/libusb/1.0.22/lib/libusb-1.0.dylib contrib/build-osx

info "Building libsecp256k1"
brew install autoconf automake libtool
git clone https://github.com/bitcoin-core/secp256k1 $BUILDDIR/secp256k1
pushd $BUILDDIR/secp256k1
git reset --hard $LIBSECP_VERSION
git clean -f -x -q
./autogen.sh
./configure --enable-module-recovery --enable-experimental --enable-module-ecdh --disable-jni
make -j4
popd
cp $BUILDDIR/secp256k1/.libs/libsecp256k1.0.dylib contrib/build-osx

info "Installing requirements..."
python3 -m pip install -Ir ./contrib/deterministic-build/requirements.txt --user && \
python3 -m pip install pyqt5 --user || \
fail "Could not install requirements"

info "Compile images..."
pyrcc5 icons.qrc -o electrum/gui/qt/icons_rc.py || fail "pyrcc5 not found"

info "Installing hardware wallet requirements..."
python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --user || \
fail "Could not install hardware wallet requirements"

info "Building Electrum..."
python3 setup.py install --user > /dev/null || fail "Could not build Electrum"

info "Building binary"
pyinstaller --noconfirm --ascii --name $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"

info "Creating .DMG"
hdiutil create -fs HFS+ -volname "Ocean Wallet" -srcfolder dist/Ocean\ Wallet.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
