#!/bin/bash

set -e

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

pkgname="zbar"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
if ! [ -x configure ] ; then
    autoreconf -vfi || fail "Could not run autoreconf for $pkgname. Please make sure you have automake and libtool installed, and try again."
fi
if ! [ -r config.status ] ; then
    ./configure \
        $AUTOCONF_FLAGS \
        --prefix="$here/$pkgname/dist" \
        --with-x=no \
        --enable-pthread=no \
        --enable-doc=no \
        --enable-video=no \
        --with-jpeg=no \
        --with-python=no \
        --with-gtk=no \
        --with-qt=no \
        --with-java=no \
        --with-imagemagick=no \
        --with-dbus=no \
        --enable-codes=qrcode \
        --disable-static \
        --enable-shared || fail "Could not configure $pkgname. Please make sure you have a C compiler installed and try again."
fi
make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
. "$here/$pkgname/dist/lib/libzbar.la"
host_strip "$here/$pkgname/dist/lib/$dlname"
cp -fpv "$here/$pkgname/dist/lib/$dlname" "$here/../lib" || fail "Could not copy the $pkgname binary to its destination"
info "$dlname has been placed in the 'lib' folder."
popd
