#!/usr/bin/python


if __name__ == '__main__':
    import sys, re, shutil, os, hashlib
    import imp
    os.chdir(os.path.dirname(os.path.realpath(__file__)))
    os.chdir('..')

    v = imp.load_source('version', 'lib/version.py')
    version = v.ELECTRUM_VERSION

    if not ( os.path.exists('packages')):
        print "The packages directory is missing."
        sys.exit()

    target = 'dist/el4a-%s'%version
    os.system('rm -rf %s'%target)
    os.mkdir(target)
    shutil.copyfile('electrum-ltc', target + '/el4a.py')
    shutil.copyfile('scripts/authenticator.py', target + '/authenticator.py')
    shutil.copytree("packages",'dist/el4a-%s/packages'%version, ignore=shutil.ignore_patterns('*.pyc'))
    shutil.copytree("lib",'dist/el4a-%s/lib'%version, ignore=shutil.ignore_patterns('*.pyc'))
    # dns is not used by android app
    os.system('rm -rf %s/packages/dns'%target)
    os.mkdir(target + '/gui')
    shutil.copyfile('gui/android.py', target + '/gui/android.py')
    open(target + '/gui/__init__.py','w').close()

    os.chdir("dist")
    # create the zip file
    os.system( "zip -qr el4a-%s.zip el4a-%s"%(version, version) )
    os.system( "rm -rf el4a-%s"%(version) )

    # change filename because some 3G carriers do not allow users to download a zip file...
    e4a_name = "el4a-%s.zip"%version
    print "dist/%s"%e4a_name

