#!/bin/bash
rm -rf dist
export PYTHONHASHSEED=22
VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii --name $VERSION contrib/osx.spec
hdiutil create -fs HFS+ -volname "Electrum-GRS" -srcfolder dist/Electrum-GRS.app dist/Electrum-GRS-$VERSION.dmg
