#!/usr/bin/python2

if __name__ == '__main__':
    import sys, re, shutil, os, hashlib
    import imp
    os.chdir(os.path.dirname(os.path.realpath(__file__)))
    os.chdir('..')

    v = imp.load_source('version', 'lib/version.py')
    version = v.ELECTRUM_VERSION

    if not ( os.path.exists('packages')):
        print "The packages directory is missing."
        sys.exit()

    target = 'dist/e4a-%s'%version
    os.system('rm -rf %s'%target)
    os.mkdir(target)
    shutil.copyfile('electrum', target + '/e4a.py')
    shutil.copyfile('scripts/authenticator.py', target + '/authenticator.py')
    shutil.copytree("packages",'dist/e4a-%s/packages'%version, ignore=shutil.ignore_patterns('*.pyc'))
    shutil.copytree("lib",'dist/e4a-%s/lib'%version, ignore=shutil.ignore_patterns('*.pyc'))
    os.mkdir(target + '/gui')
    shutil.copyfile('gui/android.py', target + '/gui/android.py')
    open(target + '/gui/__init__.py','w').close()
    os.mkdir(target + '/plugins')
    shutil.copyfile('plugins/__init__.py', target + '/plugins/__init__.py')

    os.chdir("dist")
    # create the zip file
    os.system( "zip -qr e4a-%s.zip e4a-%s"%(version, version) )
    os.system( "rm -rf e4a-%s"%(version) )

    # change filename because some 3G carriers do not allow users to download a zip file...
    e4a_name = "e4a-%s.zip"%version
    print "dist/%s"%e4a_name

