#!/bin/bash
version=`python3 -c "import electrumsys; print(electrumsys.version.ELECTRUM_VERSION)"`
sig=`./run_electrumsys -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
