#!/usr/bin/env python3
import os, sys

if __name__ == '__main__':
    username = sys.argv[1]
    os.chdir("dist")
    for name in os.listdir('.'):
        if name.endswith('asc'):
            continue
        sig_name = name + '.' + username + '.asc'
        os.system("gpg --sign --armor --detach --output %s %s"%(sig_name, name))
    os.chdir("..")
