#!/usr/bin/env python3
import os, sys

if __name__ == '__main__':
    username = sys.argv[1]
    os.chdir("dist")
    for fname in os.listdir('.'):
        if fname.endswith('asc'):
            continue
        sig_name = fname + '.' + username + '.asc'
        os.system(f"gpg --sign --armor --detach --output {sig_name} {fname}")
    os.chdir("..")
