#!/usr/bin/env python

from electrum import TcpStratumInterface

i = TcpStratumInterface('ecdsa.org', 50001)
i.start()
i.send([('blockchain.numblocks.subscribe',[])])

while True:
    r = i.responses.get(True, 100000000000)
    print r.get('result')
