#!/usr/bin/env python

from electrum import TcpStratumInterface

i = TcpStratumInterface('ecdsa.org', 50001)
i.init_socket()
i.start()
i.send([('blockchain.numblocks.subscribe',[])])

while True:
    r = i.responses.get(True, 100000000000)
    if r.get('method') == 'blockchain.numblocks.subscribe':
        print r.get('result')
