#!/usr/bin/env python
#
# Electrum - lightweight Bitcoin client
# Copyright (C) 2011 thomasv@gitorious
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import re
import sys, os
import optparse

try:
    import ecdsa  
except ImportError:
    sys.exit("Error: python-ecdsa does not seem to be installed. Try 'sudo pip install ecdsa'")

try:
    import aes
except ImportError:
    sys.exit("Error: AES does not seem to be installed. Try 'sudo pip install slowaes'")

try:
    from lib import *
except ImportError:
    from electrum import *

from decimal import Decimal

known_commands = {
    'help':'Prints this help',
    'validateaddress':'Check that the address is valid', 
    'balance': "Display the balance of your wallet or of an address.\nSyntax: balance [<address>]", 
    'contacts': "Show your list of contacts", 
    'create':'Create a wallet', 
    'restore':'Restore a wallet', 
    'payto':"""Create and broadcast a transaction.
Syntax: payto <recipient> <amount> [label]
<recipient> can be a bitcoin address or a label
options:\n  --fee, -f: set transaction fee\n  --fromaddr, -s: send from address -\n  --changeaddr, -c: send change to address
            """,
    'sendtx':
            'Broadcasts a transaction to the network. \nSyntax: sendtx <tx>\n<tx> must be in hexadecimal.',
    'password': 
            "Changes your password",
    'addresses':  
            """Shows your list of addresses.
options:
  -a: show all addresses, including change addresses
  -k: show private keys
  -b: show the balance of addresses""",

    'history':"Shows the transaction history",
    'label':'Assign a label to an item\nSyntax: label <tx_hash> <label>',
    'mktx':
        """Create a signed transaction, password protected.
Syntax: mktx <recipient> <amount> [label]
options:\n  --fee, -f: set transaction fee\n  --fromaddr, -s: send from address -\n  --changeaddr, -c: send change to address
        """,
    'seed':
            "Print the generation seed of your wallet.",
    'import': 
            'Imports a key pair\nSyntax: import <address>:<privatekey>',
    'signmessage':
            'Signs a message with a key\nSyntax: signmessage <address> <message>\nIf you want to lead or end a message with spaces, or want double spaces inside the message make sure you quote the string. I.e. " Hello  This is a weird String "',
    'verifymessage':
             'Verifies a signature\nSyntax: verifymessage <address> <signature> <message>\nIf you want to lead or end a message with spaces, or want double spaces inside the message make sure you quote the string. I.e. " Hello  This is a weird String "',
    'eval':  
             "Run python eval() on an object\nSyntax: eval <expression>\nExample: eval \"wallet.aliases\"",
    'get': 
             "Get config parameter.",
    'set': 
             "Set config parameter.",
    'deseed':
            "Remove seed from the wallet. The seed is stored in a file that has the name of the wallet plus '.seed'",
    'reseed':
            "Restore seed of the wallet. The wallet must have no seed, and the seed must match the wallet's master public key.",
    'freeze':'',
    'unfreeze':'',
    'prioritize':'',
    'unprioritize':'',
    }



offline_commands = [ 'password', 'mktx',
                     'label', 'contacts',
                     'help', 'validateaddress',
                     'signmessage', 'verifymessage',
                     'eval', 'set', 'get', 'create', 'addresses',
                     'import', 'seed',
                     'deseed','reseed',
                     'freeze','unfreeze',
                     'prioritize','unprioritize']


protected_commands = ['payto', 'password', 'mktx', 'seed', 'import','signmessage' ]

# get password routine
def prompt_password(prompt, confirm=True):
    import getpass
    if sys.stdin.isatty():
        password = getpass.getpass(prompt)
        if password and confirm:
            password2 = getpass.getpass("Confirm: ")
            if password != password2:
                sys.exit("Error: Passwords do not match.")
    else:
        password = raw_input(prompt)
    if not password:
        password = None
    return password

def arg_parser():
    usage = "usage: %prog [options] command\nCommands: "+ (', '.join(known_commands))
    parser = optparse.OptionParser(prog=usage)
    parser.add_option("-g", "--gui", dest="gui", help="User interface: qt, lite, gtk or text")
    parser.add_option("-w", "--wallet", dest="wallet_path", help="wallet path (default: electrum.dat)")
    parser.add_option("-o", "--offline", action="store_true", dest="offline", default=False, help="remain offline")
    parser.add_option("-a", "--all", action="store_true", dest="show_all", default=False, help="show all addresses")
    parser.add_option("-b", "--balance", action="store_true", dest="show_balance", default=False, help="show the balance at listed addresses")
    parser.add_option("-k", "--keys",action="store_true", dest="show_keys",default=False, help="show the private keys of listed addresses")
    parser.add_option("-f", "--fee", dest="tx_fee", default="0.005", help="set tx fee")
    parser.add_option("-F", "--fromaddr", dest="from_addr", default=None, help="set source address for payto/mktx. if it isn't in the wallet, it will ask for the private key unless supplied in the format public_key:private_key. It's not saved in the wallet.")
    parser.add_option("-c", "--changeaddr", dest="change_addr", default=None, help="set the change address for payto/mktx. default is a spare address, or the source address if it's not in the wallet")
    parser.add_option("-s", "--server", dest="server", default=None, help="set server host:port:protocol, where protocol is t or h")
    parser.add_option("-p", "--proxy", dest="proxy", default=None, help="set proxy [type:]host[:port], where type is socks4,socks5 or http")
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False, help="show debugging information")
    return parser


if __name__ == '__main__':

    parser = arg_parser()
    options, args = parser.parse_args()
    set_verbosity(options.verbose)

    # config is an object passed to the various constructors (wallet, interface, gui)
    if 'ANDROID_DATA' in os.environ:
        config_options = {'wallet_path':"/sdcard/electrum.dat", 'blockchain_headers_path':'/sdcard/sl4a/e4a-%s'%ELECTRUM_VERSION, 'gui':'android'}
    else:
        config_options = eval(str(options))
        for k, v in config_options.items():
            if v is None: config_options.pop(k)

    config = SimpleConfig(config_options)
    wallet = Wallet(config)

    if len(args)==0:
        url = None
        cmd = 'gui'
    elif len(args)==1 and re.match('^bitcoin:', args[0]):
        url = args[0]
        cmd = 'gui'
    else:
        cmd = args[0]
        firstarg = args[1] if len(args) > 1 else ''
       
    #this entire if/else block is just concerned with importing the 
    #right GUI toolkit based the GUI command line option given 
    if cmd == 'gui':
        pref_gui = config.get('gui','classic')
        if pref_gui == 'gtk':
            try:
                import lib.gui as gui
            except ImportError:
                import electrum.gui as gui
        elif pref_gui in ['classic', 'qt']:
            try:
                import lib.gui_qt as gui
            except ImportError:
                import electrum.gui_qt as gui
        elif pref_gui == 'lite':
              try:
                  import lib.gui_lite as gui
              except ImportError:
                  import electrum.gui_lite as gui
        elif pref_gui == 'text':
              try:
                  import lib.gui_text as gui
              except ImportError:
                  import electrum.gui_text as gui
        elif pref_gui == 'android':
              try:
                  import lib.gui_android as gui
              except ImportError:
                  import electrum.gui_android as gui
        else:
            sys.exit("Error: Unknown GUI: " + pref_gui )

        
        interface = Interface(config, True)
        wallet.interface = interface
        interface.start()
        interface.send([('server.peers.subscribe',[])])

        gui = gui.ElectrumGui(wallet, config)

        found = config.wallet_file_exists
        if not found:
            a = gui.restore_or_create()
            if not a: exit()
            # select a server.
            s = gui.network_dialog()

            if a =='create':
                wallet.new_seed(None)
                wallet.init_mpk( wallet.seed )
            else:
                # ask for seed and gap.
                if not gui.seed_dialog(): exit()
                wallet.init_mpk( wallet.seed )

            # generate the first addresses, in case we are offline
            wallet.synchronize()
            if a == 'create':
                # display seed
                gui.show_seed()

        verifier = WalletVerifier(interface, config)
        wallet.set_verifier(verifier)
        WalletSynchronizer(wallet, config).start()

        if not found and a == 'restore' and s is not None:
            try:
                keep_it = gui.restore_wallet()
                wallet.fill_addressbook()
            except:
                import traceback
                traceback.print_exc(file=sys.stdout)
                exit()

            if not keep_it: exit()

        if not found:
            gui.password_dialog()

        wallet.save()
        verifier.start()
        gui.main(url)
        wallet.save()
        sys.exit(0)

    if cmd not in known_commands:
        cmd = 'help'

    if not config.wallet_file_exists and cmd not in ['help','create','restore']:
        print_msg("Error: Wallet file not found.")
        print_msg("Type 'electrum create' to create a new wallet, or provide a path to a wallet with the -w option")
        sys.exit(0)
    
    if cmd in ['create', 'restore']:
        if config.wallet_file_exists:
            sys.exit("Error: Remove the existing wallet first!")
        password = prompt_password("Password (hit return if you do not wish to encrypt your wallet):")

        server = config.get('server')
        if not server: server = pick_random_server()
        w_host, w_port, w_protocol = server.split(':')
        host = raw_input("server (default:%s):"%w_host)
        port = raw_input("port (default:%s):"%w_port)
        protocol = raw_input("protocol [t=tcp;h=http;n=native] (default:%s):"%w_protocol)
        fee = raw_input("fee (default:%s):"%( str(Decimal(wallet.fee)/100000000)) )
        gap = raw_input("gap limit (default 5):")
        if host: w_host = host
        if port: w_port = port
        if protocol: w_protocol = protocol
        wallet.config.set_key('server', w_host + ':' + w_port + ':' +w_protocol)
        if fee: wallet.fee = float(fee)
        if gap: wallet.gap_limit = int(gap)

        if cmd == 'restore':
            seed = raw_input("seed:")
            try:
                seed.decode('hex')
            except:
                print_error("Warning: Not hex, trying decode.")
                seed = mnemonic_decode( seed.split(' ') )
            if not seed:
                sys.exit("Error: No seed")

            wallet.seed = str(seed)
            wallet.init_mpk( wallet.seed )
            if not options.offline:

                interface = Interface(config)
                interface.start()
                wallet.interface = interface

                verifier = WalletVerifier(interface, config)
                wallet.set_verifier(verifier)

                print_msg("Recovering wallet...")
                WalletSynchronizer(wallet, config).start()
                wallet.update()
                if wallet.is_found():
                    print_msg("Recovery successful")
                else:
                    print_msg("Warning: Found no history for this wallet")
            else:
                wallet.synchronize()
            wallet.fill_addressbook()
            wallet.save()
            print_msg("Wallet saved in '%s'"%wallet.config.path)
        else:
            wallet.new_seed(None)
            wallet.init_mpk( wallet.seed )
            wallet.synchronize() # there is no wallet thread 
            wallet.save()
            print_msg("Your wallet generation seed is: " + wallet.seed)
            print_msg("Please keep it in a safe place; if you lose it, you will not be able to restore your wallet.")
            print_msg("Equivalently, your wallet seed can be stored and recovered with the following mnemonic code:")
            print_msg("\""+' '.join(mnemonic_encode(wallet.seed))+"\"")
            print_msg("Wallet saved in '%s'"%wallet.config.path)
            
        if password:
            wallet.update_password(wallet.seed, None, password)

    # check syntax
    if cmd in ['payto', 'mktx']:
        try:
            to_address = args[1]
            amount = int( 100000000 * Decimal(args[2]) )
            change_addr = None
            label = ' '.join(args[3:])
            if options.tx_fee: 
                options.tx_fee = int( 100000000 * Decimal(options.tx_fee) )
        except:
            firstarg = cmd
            cmd = 'help'

    # open session
    if cmd not in offline_commands and not options.offline:
        interface = Interface(config)
        interface.register_callback('connected', lambda: print_error("Connected to " + interface.connection_msg))
        interface.start()
        wallet.interface = interface
        WalletSynchronizer(wallet, config).start()
        wallet.update()
        wallet.save()

    # check if --from_addr not in wallet (for mktx/payto)
    is_temporary = False
    from_addr = None
    if options.from_addr:
        from_addr = options.from_addr
        if from_addr not in wallet.all_addresses():
            is_temporary = True
                
    # important warning
    if cmd=='addresses' and options.show_keys:
        print_msg("WARNING: ALL your private keys are secret.")
        print_msg("Exposing a single private key can compromise your entire wallet!")
        print_msg("In particular, DO NOT use 'redeem private key' services proposed by third parties.")

    # commands needing password
    if cmd in protected_commands or ( cmd=='addresses' and options.show_keys):
        password = prompt_password('Password:', False) if wallet.use_encryption and not is_temporary else None
        # check password
        try:
            wallet.pw_decode( wallet.seed, password)
        except:
            print_error("Error: This password does not decode this wallet.")
            exit(1)

    if cmd == 'import':
        # See if they specificed a key on the cmd line, if not prompt
        if len(args) > 1:
            keypair = args[1]
        else:
            keypair = prompt_password('Enter Address:PrivateKey (will not echo):', False)
        try:
            wallet.import_key(keypair,password)
            wallet.save()
            print_msg("Keypair imported")
        except BaseException(e):
            print_error("Error: Keypair import failed: " + str(e))

    if cmd == 'help':
        cmd2 = firstarg
        if cmd2 not in known_commands:
            parser.print_help()
            print_msg("Type 'electrum help <command>' to see the help for a specific command")
            print_msg("Type 'electrum --help' to see the list of options")
            print_msg("List of commands:", ', '.join(known_commands))
        else:
            print_msg(known_commands[cmd2])

    elif cmd == 'seed':
        seed = wallet.pw_decode( wallet.seed, password)
        print_msg(seed + ' "' + ' '.join(mnemonic_encode(seed)) + '"')

    elif cmd == 'deseed':
        if not wallet.seed:
            print_error("Error: This wallet has no seed")
        elif wallet.use_encryption:
            print_error("Error: This wallet is encrypted")
        else:
            ns = wallet.config.path + '.seed'
            print_msg("Warning: you are going to extract the seed from '%s'\nThe seed will be saved in '%s'"%(wallet.config.path,ns))
            if raw_input("Are you sure you want to continue? (y/n) ") in ['y','Y','yes']:
                f = open(ns,'w')
                f.write(repr({'seed':wallet.seed, 'imported_keys':wallet.imported_keys})+"\n")
                f.close()
                wallet.seed = ''
                for k in wallet.imported_keys.keys(): wallet.imported_keys[k] = ''
                wallet.save()
                print_msg("Done.")
            else:
                print_error("Action canceled.")

    elif cmd == 'reseed':
        if wallet.seed:
            print_msg("Warning: This wallet already has a seed", wallet.seed)
        else:
            ns = wallet.config.path + '.seed'
            try:
                f = open(ns,'r')
                data = f.read()
                f.close()
            except IOError:
                sys.exit("Error: Seed file not found")
            try:
                import ast
                d = ast.literal_eval( data )
                seed = d['seed']
                imported_keys = d.get('imported_keys',{})
            except:
                sys.exit("Error: Error with seed file")

            mpk = wallet.master_public_key
            wallet.seed = seed
            wallet.imported_keys = imported_keys
            wallet.use_encryption = False
            wallet.init_mpk(seed)
            if mpk == wallet.master_public_key:
                wallet.save()
                print_msg("Done: " + wallet.config.path)
            else:
                print_error("Error: Master public key does not match")

    elif cmd == 'validateaddress':
        addr = args[1]
        print_msg(wallet.is_valid(addr))

    elif cmd == 'balance':
        try:
            addrs = args[1:]
        except:
            pass
        if addrs == []:
            c, u = wallet.get_balance()
            if u:
                print_msg(Decimal( c ) / 100000000 , Decimal( u ) / 100000000)
            else:
                print_msg(Decimal( c ) / 100000000)
        else:
            for addr in addrs:
                c, u = wallet.get_addr_balance(addr)
                if u:
                    print_msg("%s %s, %s" % (addr, str(Decimal(c)/100000000), str(Decimal(u)/100000000)))
                else:
                    print_msg("%s %s" % (addr, str(Decimal(c)/100000000)))

    elif cmd in [ 'contacts']:
        for addr in wallet.addressbook:
            print_msg(addr, "   ", wallet.labels.get(addr))

    elif cmd == 'eval':
        print_msg(eval(args[1]))
        wallet.save()

    elif cmd == 'get':
        key = args[1]
        print_msg(wallet.config.get(key))

    elif cmd == 'set':
        key, value = args[1:3]
        if key not in ['seed', 'seed_version', 'master_public_key', 'use_encryption']:
            wallet.config.set_key(key, value, True)
            print_msg(True)
        else:
            print_msg(False)

    elif cmd in [ 'addresses']:
        for addr in wallet.all_addresses():
            if options.show_all or not wallet.is_change(addr):

                flags = wallet.get_address_flags(addr)
                label = wallet.labels.get(addr,'')
                
                if label: label = "\"%s\""%label

                if options.show_balance:
                    h = wallet.history.get(addr,[])
                    #ni = no = 0
                    #for item in h:
                    #    if item['is_input']:  ni += 1
                    #    else:              no += 1
                    b = format_satoshis(wallet.get_addr_balance(addr)[0])
                else: b=''
                m_addr = "%34s"%addr
                if options.show_keys:
                    m_addr += ':' + str(wallet.get_private_key_base58(addr, password))
                print_msg(flags, m_addr, b, label)

    if cmd == 'history':
        import datetime
        for item in wallet.get_tx_history():
            tx_hash, conf, is_mine, value, fee, balance, timestamp = item
            try:
                time_str = datetime.datetime.fromtimestamp( timestamp).isoformat(' ')[:-3]
            except:
                time_str = "----"

            label, is_default_label = wallet.get_label(tx_hash)
            if not label: label = tx_hash
            else: label = label + ' '*(64 - len(label) )

            print_msg("%17s"%time_str, "  " + label + "  " + format_satoshis(value)+ "  "+ format_satoshis(balance))
        print_msg("# balance: ", format_satoshis(balance))

    elif cmd == 'label':
        try:
            tx = args[1]
            label = ' '.join(args[2:])
        except:
            print_error("Error. Syntax:  label <tx_hash> <text>")
            sys.exit(1)
        wallet.labels[tx] = label
        wallet.save()
            
    elif cmd in ['payto', 'mktx']:
        if from_addr and is_temporary:
            if from_addr.find(":") == -1:
                keypair = from_addr + ":" + prompt_password('Private key:', False)
            else:
                keypair = from_addr
                from_addr = keypair.split(':')[0]
            if not wallet.import_key(keypair,password):
                print_error("Error: Invalid key pair")
                exit(1)
            wallet.history[from_addr] = interface.retrieve_history(from_addr)
            wallet.update_tx_history()
            change_addr = from_addr

        if options.change_addr:
            change_addr = options.change_addr

        for k, v in wallet.labels.items():
            if v == to_address:
                to_address = k
                print_msg("alias", to_address)
                break
            if change_addr and v == change_addr:
                change_addr = k
        try:
            tx = wallet.mktx( to_address, amount, label, password,
                fee = options.tx_fee, change_addr = change_addr, from_addr = from_addr )
        except:
            import traceback
            traceback.print_exc(file=sys.stdout)
            tx = None

        if tx and cmd=='payto': 
            r, h = wallet.sendtx( tx )
            print_msg(h)
        else:
            print_msg(tx)

        if is_temporary:
            wallet.imported_keys.pop(from_addr)
            del(wallet.history[from_addr])
        wallet.save()

    elif cmd == 'sendtx':
        tx = args[1]
        r, h = wallet.sendtx( tx )
        print_msg(h)

    elif cmd == 'password':
        try:
            seed = wallet.pw_decode( wallet.seed, password)
        except ValueError:
            sys.exit("Error: Password does not decrypt this wallet.")

        new_password = prompt_password('New password:')
        wallet.update_password(seed, password, new_password)

    elif cmd == 'signmessage':
        if len(args) < 3:
            print_error("Error: Invalid usage of signmessage.")
            print_msg(known_commands[cmd])
            sys.exit(1)
        address = args[1]
        message = ' '.join(args[2:])
        if len(args) > 3:
            print_msg("Warning: Message was reconstructed from several arguments:", repr(message))
        print_msg(wallet.sign_message(address, message, password))

    elif cmd == 'verifymessage':
        try:
            address = args[1]
            signature = args[2]
            message = ' '.join(args[3:])
        except:
            print_error("Error: Not all parameters were given, displaying help instead.")
            print_msg(known_commands[cmd])
            sys.exit(1)
        if len(args) > 4:
            print_msg("Warning: Message was reconstructed from several arguments:", repr(message))
        try:
            wallet.verify_message(address, signature, message)
            print_msg(True)
        except BaseException as e:
            print_error("Verification error: {0}".format(e))
            print_msg(False)

    elif cmd == 'freeze':
        addr = args[1]
        print_msg(wallet.freeze(addr))
        
    elif cmd == 'unfreeze':
        addr = args[1]
        print_msg(wallet.unfreeze(addr))

    elif cmd == 'prioritize':
        addr = args[1]
        print_msg(wallet.prioritize(addr))

    elif cmd == 'unprioritize':
        addr = args[1]
        print_msg(wallet.unprioritize(addr))

