#!/usr/bin/env python

import sys
from electrum import TcpStratumInterface

try:
    addr = sys.argv[1]
except:
    print "usage: get_history <bitcoin_address>"
    sys.exit(1)

i = TcpStratumInterface('ecdsa.org', 50001)
i.init_socket()
i.start()
i.send([('blockchain.address.get_history',[addr])])

while True:
    r = i.responses.get(True, 100000000000)
    method = r.get('method') 
    if method == 'blockchain.address.get_history':
        confirmed = unconfirmed = 0
        h = r.get('result')
        for item in h:
            print item['tx_hash'], item['value']

        break
