#!/usr/bin/env python

import interface

i = interface.TcpStratumInterface('ecdsa.org', 50001)
i.start()
i.send([('server.peers.subscribe',[])])

while True:
    r = i.responses.get(True, 100000000000)
    print r.get('result')
