#!/bin/sh

# Electron Cash - lightweight Bitcoin client
# Copyright (C) 2019 Axel Gembe <derago@gmail.com>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e
set -x

here=$(dirname $(realpath "$0"))
. "$here"/../base.sh # functions we use below (fail, et al)

SRCURL="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"
SRCNAME=$(basename $SRCURL)
SRCPATH="$here/$SRCNAME"

if ! [ -e "$SRCPATH" ] ; then
    info "Downloading source file"
    wget -O "$SRCPATH" "$SRCURL"
fi

(
    info "Unzipping source file"
    rm -rf "$here"/unzipped
    mkdir "$here"/unzipped
    cd "$here"/unzipped
    unzip "$SRCPATH"
)

SRCTTF="$here"/unzipped/NotoColorEmoji.ttf

pyftsubset "$SRCTTF" --unicodes-file="$here"/emojis.txt --output-file="$here"/emojis.ttf

rm -rf "$here"/unzipped
