#!/bin/bash
###########
## work in progress
## makes installable deb file
## plus self-installer. 
## doesn't fully install deps
##
VERSION="$1"

apt-get install -y python-all debhelper
pip install stdeb
mkdir -pv /root/repo/debian_package/Encompass-${VERSION}

cd /root/encompass-release/ltc_scrypt-1.0
python setup.py bdist
cp dist/ltc_scrypt-1.0.linux-x86_64.tar.gz /root/repo/debian_package/Encompass-${VERSION}
cd ..
cd /root/encompass-release/darkcoin_hash-1.1
python setup.py  bdist
cp dist/darkcoin_hash-1.1.linux-x86_64.tar.gz /root/repo/debian_package/Encompass-${VERSION}
cd ..
cd /root/repo
python setup.py --command-packages=stdeb.command bdist_deb
cp deb_dist/python-* /root/repo/debian_package/Encompass-${VERSION}
cd ..
cd /root/repo/debian_package
tar -cpzvf encompass-${VERSION}_ubuntu.tar.gz Encompass-${VERSION}


cat /root/debian-installer.sh encompass-${VERSION}_ubuntu.tar.gz  > encompass-${VERSION}_ubuntu
chmod +x encompass-${VERSION}_ubuntu


