#!/usr/bin/env bash                                                                                                                                                                                               

src_dir=$(dirname "$0")
cd "$src_dir/../.."

rm -rf dmg1
hdiutil attach $1
cp -r /Volumes/Electrum/Electrum.app/ dmg1
hdiutil detach /Volumes/Electrum

rm -rf dmg2
hdiutil attach $1
cp -r /Volumes/Electrum/Electrum.app/ dmg2
hdiutil detach /Volumes/Electrum

# remove signatures
for i in $(find dmg1/ ); do codesign --remove-signature $i; done;
for i in $(find dmg2/ ); do codesign --remove-signature $i; done;

diff=$(diff -qr dmg1 dmg2)
echo $diff
if [ "$diff" ]
then
    echo "failure"
else
    echo "success"
fi
