FROM ubuntu:18.04@sha256:5f4bdc3467537cbbe563e80db2c3ec95d548a9145d64453b06939c4592d67b6d

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apt-get update -q && \
    apt-get install -qy \
        git=1:2.17.1-1ubuntu0.5 \
        wget=1.19.4-1ubuntu2.1 \
        make=4.1-9.1ubuntu1 \
        autotools-dev=20180224.1 \
        autoconf=2.69-11 \
        libtool=2.4.6-2 \
        xz-utils=5.2.2-1.3 \
        libssl-dev=1.1.0g-2ubuntu4.3 \
        zlib1g-dev=1:1.2.11.dfsg-0ubuntu2 \
        libffi6=3.2.1-8 \
        libffi-dev=3.2.1-8 \
        libncurses5-dev=6.1-1ubuntu1.18.04 \
        libsqlite3-dev=3.22.0-1 \
        libusb-1.0-0-dev=2:1.0.21-2 \
        libudev-dev=237-3ubuntu10.17 \
        gettext=0.19.8.1-6ubuntu0.1 \
        libzbar0=0.10+doc-10.1build2 \
        faketime=0.9.7-2 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
