FROM ubuntu:16.04@sha256:a4d8e674ee993e5ec88823391de828a5e9286a1597b731eaecaaf9066cfdf539

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apt-get update -q && \
    apt-get install -qy \
        git=1:2.7.4-0ubuntu1.6 \
        wget=1.17.1-1ubuntu1.5 \
        make=4.1-6 \
        autotools-dev=20150820.1 \
        autoconf=2.69-9 \
        libtool=2.4.6-0.1 \
        xz-utils=5.1.1alpha+20120614-2ubuntu2 \
        libffi-dev=3.2.1-4 \
        libncurses5-dev=6.0+20160213-1ubuntu1 \
        libsqlite3-dev=3.11.0-1ubuntu1.2 \
        libusb-1.0-0-dev=2:1.0.20-1 \
        libudev-dev=229-4ubuntu21.21 \
        gettext=0.19.7-2ubuntu3.1 \
        pkg-config=0.29.1-0ubuntu1 \
        libdbus-1-3=1.10.6-1ubuntu3.4 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

# Hack to switch from xenial to bionic. Normally you shouldn't mix these but
# if you do, you need to make sure that what you install doesn't cause
# conflicts. Best to install only packages with very few dependencies from
# the newer version.
RUN sed -i -e 's/xenial/bionic/' /etc/apt/sources.list

# The Ubuntu 16.04 freetype / fontconfig does not seem to properly support
# color emojis. To support those we get a newer freetype / fontconfig combo
# from the Ubuntu 18.04 repo.
# We also install OpenSSL 1.1 to have that be available accross all the
# platforms we support.
RUN apt-get update -q && \
    apt-get install -qy \
        zlib1g-dev=1:1.2.11.dfsg-0ubuntu2 \
        libfreetype6=2.8.1-2ubuntu2 \
        libfontconfig1=2.12.6-0ubuntu2 \
        libssl-dev=1.1.0g-2ubuntu4 \
        libssl1.1=1.1.0g-2ubuntu4 \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
