# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x65xchange.proto\"G\n\x0f\x45xchangeAddress\x12\x11\n\tcoin_type\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65st_tag\x18\x03 \x01(\t\"\xcc\x02\n\x12\x45xchangeResponseV2\x12)\n\x0f\x64\x65posit_address\x18\x01 \x01(\x0b\x32\x10.ExchangeAddress\x12\x16\n\x0e\x64\x65posit_amount\x18\x02 \x01(\x0c\x12\x12\n\nexpiration\x18\x03 \x01(\x03\x12\x13\n\x0bquoted_rate\x18\x04 \x01(\x0c\x12,\n\x12withdrawal_address\x18\x05 \x01(\x0b\x32\x10.ExchangeAddress\x12\x19\n\x11withdrawal_amount\x18\x06 \x01(\x0c\x12(\n\x0ereturn_address\x18\x07 \x01(\x0b\x32\x10.ExchangeAddress\x12\x0f\n\x07\x61pi_key\x18\x08 \x01(\x0c\x12\x11\n\tminer_fee\x18\t \x01(\x0c\x12\x10\n\x08order_id\x18\n \x01(\x0c\x12!\n\x04type\x18\x0b \x01(\x0e\x32\n.OrderType:\x07Precise\"T\n\x16SignedExchangeResponse\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\'\n\nresponseV2\x18\x03 \x01(\x0b\x32\x13.ExchangeResponseV2*#\n\tOrderType\x12\x0b\n\x07Precise\x10\x00\x12\t\n\x05Quick\x10\x01\x42.\n\x1b\x63om.keepkey.device-protocolB\x0fKeepKeyExchange')
)

_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='OrderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Precise', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Quick', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=512,
  serialized_end=547,
)
_sym_db.RegisterEnumDescriptor(_ORDERTYPE)

OrderType = enum_type_wrapper.EnumTypeWrapper(_ORDERTYPE)
Precise = 0
Quick = 1



_EXCHANGEADDRESS = _descriptor.Descriptor(
  name='ExchangeAddress',
  full_name='ExchangeAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coin_type', full_name='ExchangeAddress.coin_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ExchangeAddress.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_tag', full_name='ExchangeAddress.dest_tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=89,
)


_EXCHANGERESPONSEV2 = _descriptor.Descriptor(
  name='ExchangeResponseV2',
  full_name='ExchangeResponseV2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deposit_address', full_name='ExchangeResponseV2.deposit_address', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit_amount', full_name='ExchangeResponseV2.deposit_amount', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='ExchangeResponseV2.expiration', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quoted_rate', full_name='ExchangeResponseV2.quoted_rate', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdrawal_address', full_name='ExchangeResponseV2.withdrawal_address', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdrawal_amount', full_name='ExchangeResponseV2.withdrawal_amount', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_address', full_name='ExchangeResponseV2.return_address', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_key', full_name='ExchangeResponseV2.api_key', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='miner_fee', full_name='ExchangeResponseV2.miner_fee', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='ExchangeResponseV2.order_id', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ExchangeResponseV2.type', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=424,
)


_SIGNEDEXCHANGERESPONSE = _descriptor.Descriptor(
  name='SignedExchangeResponse',
  full_name='SignedExchangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='SignedExchangeResponse.signature', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseV2', full_name='SignedExchangeResponse.responseV2', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=510,
)

_EXCHANGERESPONSEV2.fields_by_name['deposit_address'].message_type = _EXCHANGEADDRESS
_EXCHANGERESPONSEV2.fields_by_name['withdrawal_address'].message_type = _EXCHANGEADDRESS
_EXCHANGERESPONSEV2.fields_by_name['return_address'].message_type = _EXCHANGEADDRESS
_EXCHANGERESPONSEV2.fields_by_name['type'].enum_type = _ORDERTYPE
_SIGNEDEXCHANGERESPONSE.fields_by_name['responseV2'].message_type = _EXCHANGERESPONSEV2
DESCRIPTOR.message_types_by_name['ExchangeAddress'] = _EXCHANGEADDRESS
DESCRIPTOR.message_types_by_name['ExchangeResponseV2'] = _EXCHANGERESPONSEV2
DESCRIPTOR.message_types_by_name['SignedExchangeResponse'] = _SIGNEDEXCHANGERESPONSE
DESCRIPTOR.enum_types_by_name['OrderType'] = _ORDERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExchangeAddress = _reflection.GeneratedProtocolMessageType('ExchangeAddress', (_message.Message,), dict(
  DESCRIPTOR = _EXCHANGEADDRESS,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeAddress)
  ))
_sym_db.RegisterMessage(ExchangeAddress)

ExchangeResponseV2 = _reflection.GeneratedProtocolMessageType('ExchangeResponseV2', (_message.Message,), dict(
  DESCRIPTOR = _EXCHANGERESPONSEV2,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeResponseV2)
  ))
_sym_db.RegisterMessage(ExchangeResponseV2)

SignedExchangeResponse = _reflection.GeneratedProtocolMessageType('SignedExchangeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIGNEDEXCHANGERESPONSE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:SignedExchangeResponse)
  ))
_sym_db.RegisterMessage(SignedExchangeResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033com.keepkey.device-protocolB\017KeepKeyExchange'))
# @@protoc_insertion_point(module_scope)
