# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-nano.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-nano.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13messages-nano.proto\x1a\x0btypes.proto\"R\n\x0eNanoGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x17\n\tcoin_name\x18\x02 \x01(\t:\x04Nano\x12\x14\n\x0cshow_display\x18\x03 \x01(\x08\"\x1e\n\x0bNanoAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xd6\x02\n\nNanoSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x17\n\tcoin_name\x18\x02 \x01(\t:\x04Nano\x12-\n\x0cparent_block\x18\x03 \x01(\x0b\x32\x17.NanoSignTx.ParentBlock\x12\x11\n\tlink_hash\x18\x04 \x01(\x0c\x12\x16\n\x0elink_recipient\x18\x05 \x01(\t\x12\x18\n\x10link_recipient_n\x18\x06 \x03(\r\x12\x16\n\x0erepresentative\x18\x07 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x08 \x01(\x0c\x12$\n\rexchange_type\x18\t \x01(\x0b\x32\r.ExchangeType\x1aY\n\x0bParentBlock\x12\x13\n\x0bparent_hash\x18\x01 \x01(\x0c\x12\x0c\n\x04link\x18\x02 \x01(\x0c\x12\x16\n\x0erepresentative\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x0c\"5\n\x0cNanoSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x12\n\nblock_hash\x18\x02 \x01(\x0c\x42\x30\n\x1a\x63om.keepkey.deviceprotocolB\x12KeepKeyMessageNano')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_NANOGETADDRESS = _descriptor.Descriptor(
  name='NanoGetAddress',
  full_name='NanoGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='NanoGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='NanoGetAddress.coin_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Nano").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='NanoGetAddress.show_display', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=118,
)


_NANOADDRESS = _descriptor.Descriptor(
  name='NanoAddress',
  full_name='NanoAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='NanoAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=150,
)


_NANOSIGNTX_PARENTBLOCK = _descriptor.Descriptor(
  name='ParentBlock',
  full_name='NanoSignTx.ParentBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent_hash', full_name='NanoSignTx.ParentBlock.parent_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link', full_name='NanoSignTx.ParentBlock.link', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='representative', full_name='NanoSignTx.ParentBlock.representative', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='NanoSignTx.ParentBlock.balance', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=495,
)

_NANOSIGNTX = _descriptor.Descriptor(
  name='NanoSignTx',
  full_name='NanoSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='NanoSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='NanoSignTx.coin_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Nano").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_block', full_name='NanoSignTx.parent_block', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_hash', full_name='NanoSignTx.link_hash', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_recipient', full_name='NanoSignTx.link_recipient', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_recipient_n', full_name='NanoSignTx.link_recipient_n', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='representative', full_name='NanoSignTx.representative', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='NanoSignTx.balance', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange_type', full_name='NanoSignTx.exchange_type', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NANOSIGNTX_PARENTBLOCK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=495,
)


_NANOSIGNEDTX = _descriptor.Descriptor(
  name='NanoSignedTx',
  full_name='NanoSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='NanoSignedTx.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_hash', full_name='NanoSignedTx.block_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=550,
)

_NANOSIGNTX_PARENTBLOCK.containing_type = _NANOSIGNTX
_NANOSIGNTX.fields_by_name['parent_block'].message_type = _NANOSIGNTX_PARENTBLOCK
_NANOSIGNTX.fields_by_name['exchange_type'].message_type = types__pb2._EXCHANGETYPE
DESCRIPTOR.message_types_by_name['NanoGetAddress'] = _NANOGETADDRESS
DESCRIPTOR.message_types_by_name['NanoAddress'] = _NANOADDRESS
DESCRIPTOR.message_types_by_name['NanoSignTx'] = _NANOSIGNTX
DESCRIPTOR.message_types_by_name['NanoSignedTx'] = _NANOSIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NanoGetAddress = _reflection.GeneratedProtocolMessageType('NanoGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _NANOGETADDRESS,
  __module__ = 'messages_nano_pb2'
  # @@protoc_insertion_point(class_scope:NanoGetAddress)
  ))
_sym_db.RegisterMessage(NanoGetAddress)

NanoAddress = _reflection.GeneratedProtocolMessageType('NanoAddress', (_message.Message,), dict(
  DESCRIPTOR = _NANOADDRESS,
  __module__ = 'messages_nano_pb2'
  # @@protoc_insertion_point(class_scope:NanoAddress)
  ))
_sym_db.RegisterMessage(NanoAddress)

NanoSignTx = _reflection.GeneratedProtocolMessageType('NanoSignTx', (_message.Message,), dict(

  ParentBlock = _reflection.GeneratedProtocolMessageType('ParentBlock', (_message.Message,), dict(
    DESCRIPTOR = _NANOSIGNTX_PARENTBLOCK,
    __module__ = 'messages_nano_pb2'
    # @@protoc_insertion_point(class_scope:NanoSignTx.ParentBlock)
    ))
  ,
  DESCRIPTOR = _NANOSIGNTX,
  __module__ = 'messages_nano_pb2'
  # @@protoc_insertion_point(class_scope:NanoSignTx)
  ))
_sym_db.RegisterMessage(NanoSignTx)
_sym_db.RegisterMessage(NanoSignTx.ParentBlock)

NanoSignedTx = _reflection.GeneratedProtocolMessageType('NanoSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _NANOSIGNEDTX,
  __module__ = 'messages_nano_pb2'
  # @@protoc_insertion_point(class_scope:NanoSignedTx)
  ))
_sym_db.RegisterMessage(NanoSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.keepkey.deviceprotocolB\022KeepKeyMessageNano'))
# @@protoc_insertion_point(module_scope)
