# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-cosmos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-cosmos.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15messages-cosmos.proto\x1a\x0btypes.proto\";\n\x10\x43osmosGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x14\n\x0cshow_display\x18\x02 \x01(\x08\" \n\rCosmosAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xa7\x01\n\x0c\x43osmosSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x1a\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x12\n\nfee_amount\x18\x04 \x01(\r\x12\x0b\n\x03gas\x18\x05 \x01(\r\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x14\n\x08sequence\x18\x07 \x01(\x04\x42\x02\x30\x01\x12\x11\n\tmsg_count\x18\x08 \x01(\r\"\x12\n\x10\x43osmosMsgRequest\",\n\x0c\x43osmosMsgAck\x12\x1c\n\x04send\x18\x01 \x01(\x0b\x32\x0e.CosmosMsgSend\"\x9d\x01\n\rCosmosMsgSend\x12\x14\n\x0c\x66rom_address\x18\x06 \x01(\t\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x12\n\x06\x61mount\x18\x08 \x01(\x04\x42\x02\x30\x01\x12(\n\x0c\x61\x64\x64ress_type\x18\t \x01(\x0e\x32\x12.OutputAddressType\x12$\n\rexchange_type\x18\n \x01(\x0b\x32\r.ExchangeType\"7\n\x0e\x43osmosSignedTx\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42\x32\n\x1a\x63om.keepkey.deviceprotocolB\x14KeepKeyMessageCosmos')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_COSMOSGETADDRESS = _descriptor.Descriptor(
  name='CosmosGetAddress',
  full_name='CosmosGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='CosmosGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='CosmosGetAddress.show_display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=97,
)


_COSMOSADDRESS = _descriptor.Descriptor(
  name='CosmosAddress',
  full_name='CosmosAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='CosmosAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=131,
)


_COSMOSSIGNTX = _descriptor.Descriptor(
  name='CosmosSignTx',
  full_name='CosmosSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='CosmosSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='CosmosSignTx.account_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='CosmosSignTx.chain_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_amount', full_name='CosmosSignTx.fee_amount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas', full_name='CosmosSignTx.gas', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='CosmosSignTx.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='CosmosSignTx.sequence', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='CosmosSignTx.msg_count', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=301,
)


_COSMOSMSGREQUEST = _descriptor.Descriptor(
  name='CosmosMsgRequest',
  full_name='CosmosMsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=321,
)


_COSMOSMSGACK = _descriptor.Descriptor(
  name='CosmosMsgAck',
  full_name='CosmosMsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send', full_name='CosmosMsgAck.send', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=367,
)


_COSMOSMSGSEND = _descriptor.Descriptor(
  name='CosmosMsgSend',
  full_name='CosmosMsgSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_address', full_name='CosmosMsgSend.from_address', index=0,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='CosmosMsgSend.to_address', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CosmosMsgSend.amount', index=2,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_type', full_name='CosmosMsgSend.address_type', index=3,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange_type', full_name='CosmosMsgSend.exchange_type', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=527,
)


_COSMOSSIGNEDTX = _descriptor.Descriptor(
  name='CosmosSignedTx',
  full_name='CosmosSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='CosmosSignedTx.public_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='CosmosSignedTx.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=584,
)

_COSMOSMSGACK.fields_by_name['send'].message_type = _COSMOSMSGSEND
_COSMOSMSGSEND.fields_by_name['address_type'].enum_type = types__pb2._OUTPUTADDRESSTYPE
_COSMOSMSGSEND.fields_by_name['exchange_type'].message_type = types__pb2._EXCHANGETYPE
DESCRIPTOR.message_types_by_name['CosmosGetAddress'] = _COSMOSGETADDRESS
DESCRIPTOR.message_types_by_name['CosmosAddress'] = _COSMOSADDRESS
DESCRIPTOR.message_types_by_name['CosmosSignTx'] = _COSMOSSIGNTX
DESCRIPTOR.message_types_by_name['CosmosMsgRequest'] = _COSMOSMSGREQUEST
DESCRIPTOR.message_types_by_name['CosmosMsgAck'] = _COSMOSMSGACK
DESCRIPTOR.message_types_by_name['CosmosMsgSend'] = _COSMOSMSGSEND
DESCRIPTOR.message_types_by_name['CosmosSignedTx'] = _COSMOSSIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CosmosGetAddress = _reflection.GeneratedProtocolMessageType('CosmosGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSGETADDRESS,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosGetAddress)
  ))
_sym_db.RegisterMessage(CosmosGetAddress)

CosmosAddress = _reflection.GeneratedProtocolMessageType('CosmosAddress', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSADDRESS,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosAddress)
  ))
_sym_db.RegisterMessage(CosmosAddress)

CosmosSignTx = _reflection.GeneratedProtocolMessageType('CosmosSignTx', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSSIGNTX,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosSignTx)
  ))
_sym_db.RegisterMessage(CosmosSignTx)

CosmosMsgRequest = _reflection.GeneratedProtocolMessageType('CosmosMsgRequest', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSMSGREQUEST,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosMsgRequest)
  ))
_sym_db.RegisterMessage(CosmosMsgRequest)

CosmosMsgAck = _reflection.GeneratedProtocolMessageType('CosmosMsgAck', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSMSGACK,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosMsgAck)
  ))
_sym_db.RegisterMessage(CosmosMsgAck)

CosmosMsgSend = _reflection.GeneratedProtocolMessageType('CosmosMsgSend', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSMSGSEND,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosMsgSend)
  ))
_sym_db.RegisterMessage(CosmosMsgSend)

CosmosSignedTx = _reflection.GeneratedProtocolMessageType('CosmosSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _COSMOSSIGNEDTX,
  __module__ = 'messages_cosmos_pb2'
  # @@protoc_insertion_point(class_scope:CosmosSignedTx)
  ))
_sym_db.RegisterMessage(CosmosSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.keepkey.deviceprotocolB\024KeepKeyMessageCosmos'))
_COSMOSSIGNTX.fields_by_name['account_number'].has_options = True
_COSMOSSIGNTX.fields_by_name['account_number']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_COSMOSSIGNTX.fields_by_name['sequence'].has_options = True
_COSMOSSIGNTX.fields_by_name['sequence']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_COSMOSMSGSEND.fields_by_name['amount'].has_options = True
_COSMOSMSGSEND.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
# @@protoc_insertion_point(module_scope)
