#!/usr/bin/env python

# A simple script that connects to a server and displays block headers

import time, sys, electrum

try:
    s = sys.argv[1]
except:
    s = 'ecdsa.net:50002:s'

# 1. start the interface and wait for connection
interface = electrum.Interface(s)
interface.start(wait = True)
if not interface.is_connected:
    print "cound not not connect", s
    exit()

# 2. send the subscription
callback = lambda _,result: electrum.print_json(result.get('result'))
interface.send([('blockchain.headers.subscribe',[])], callback)

# 3. wait for results
while interface.is_connected:
    time.sleep(1)
