#!/usr/bin/env python

import electrum

i = electrum.Interface()
i.start()
i.send([('blockchain.numblocks.subscribe',[])])

while True:
    try:
        r = i.get_response()
    except KeyboardInterrupt:
        break
    if r.get('method') == 'blockchain.numblocks.subscribe':
        print r.get('result')
