#!/usr/bin/env python

from electrum import Interface

i = Interface({'server':'electrum.novit.ro:50001:t'})
i.init_socket()
i.start()
i.send([('blockchain.numblocks.subscribe',[])])

while True:
    try:
        r = i.responses.get(True, 100000000000)
    except KeyboardInterrupt:
        break
    if r.get('method') == 'blockchain.numblocks.subscribe':
        print r.get('result')
