#!/usr/bin/env python

import sys
from electrum_ltc import Network, print_json

try:
    addr = sys.argv[1]
except Exception:
    print "usage: get_history <litecoin_address>"
    sys.exit(1)

n = Network()
n.start()
h = n.synchronous_get(('blockchain.address.get_history',[addr]))
print_json(h)
