#!/usr/bin/env python

import sys
from electrum_ltc import NetworkProxy, print_json

try:
    addr = sys.argv[1]
except Exception:
    print "usage: get_history <litecoin_address>"
    sys.exit(1)

n = NetworkProxy()
n.start(start_daemon=True)
h = n.synchronous_get([ ('blockchain.address.get_history',[addr]) ])[0]
print_json(h)

