#!/usr/bin/env python

from electrum import Interface

i = Interface({'server':'electrum.be:50001:t'})
i.start()
i.send([('server.peers.subscribe',[])])

while True:
    r = i.get_response()
    print r.get('result')
