#!/usr/bin/env python

from electrum import Interface

i = Interface({'server':'electrum.novit.ro:50001:t'})
i.start()
i.send([('server.peers.subscribe',[])])

while True:
    r = i.responses.get(True, 100000000000)
    print r.get('result')
