#!/usr/bin/env python

import sys, time
from electrum import Interface

try:
    addr = sys.argv[1]
except:
    print "usage: watch_address <bitcoin_address>"
    sys.exit(1)

i = Interface({'server':'ecdsa.org:50001:t'})
i.start()
i.send([('blockchain.address.subscribe',[addr])] )
time.sleep(1)

while True:
    r = i.get_response()
    method = r.get('method') 
    if method == 'blockchain.address.subscribe':
        #i.send([('blockchain.address.get_history',[addr])])
        print r
        
    elif method == 'blockchain.address.get_history':
        confirmed = unconfirmed = 0
        h = r.get('result')
        if h is None:
            continue
        for item in h:
            v = item['value']
            if item['height']:
                confirmed += v
            else:
                unconfirmed += v
        print (confirmed+unconfirmed)/1.e8


