Popup:
    title: _('Plugins')
    id: popup
    BoxLayout:
        orientation: 'vertical'

        GridLayout:
            cols: 2
            size_hint: 1, None
            height: '100dp'
            id: plugins_list
            on_parent:
                app.show_plugins(plugins_list)
        Button:
            size_hint: 1, None
            height: '48dp'
            text: _('Close')
            on_release: popup.dismiss()

        Widget:
            size_hint: 1, 0.8
